<?xml version="1.0"?>
<package format="2">
  <name>tinyhelm</name>
  <version>1.0.0</version>
  <description>An IvP-Helm inspired marine navigation package..</description>
  
  <maintainer email="vid.rijavec@gmail.com">MoffKalast</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <export>
    <metapackage/>
  </export>
</package>
