<package format="2">
	<name>tinyhelm_sim</name>
	<version>1.0.0</version>
	<description>A package for simulating a simple ASV.</description>

	<maintainer email="vid.rijavec@fri.uni-lj.si">Vid Rijavec</maintainer>
	<author>Vid Rijavec</author>
	<license>BSD</license>

	<buildtool_depend>catkin</buildtool_depend>

	<build_depend>rospy</build_depend>

	<depend>tf</depend>
	<depend>tf2_ros</depend>
	<depend>python3-pyproj</depend>
	<depend>python3-pil</depend>
	<depend>python3-requests</depend>
	<depend>python3-numpy</depend>
	<depend>python3-scipy</depend>

	<exec_depend>rospy</exec_depend>
	<exec_depend>std_msgs</exec_depend>
	<exec_depend>geometry_msgs</exec_depend>
	<exec_depend>sensor_msgs</exec_depend>
	<exec_depend>visualization_msgs</exec_depend>
	<exec_depend>nav_msgs</exec_depend>

</package>
